name: make build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
# first set up python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
# then execute the actual build process
    - name: Execute the make Build
      run: make
# the remove mopitpy
    - name: Purge local moptipy installation
      run: |
        pip uninstall -y moptipy
# and attempt to install it again from github
    - name: Install moptipy from github
      run: |
        pip install git+https://github.com/thomasWeise/moptipy.git
        python -c "import moptipy"
# fix urls in documentation
    - name: fix documentation urls
      run: |
        find /home/runner/work/bookbuilderpy/moptipy/docs/build/ \( -type d -name .git -prune \) -o -type f -name "*.html" -print0 | xargs -0 sed -i 's/ href=\"_static\// href=\"\/moptipy\/_static\//g'
        find /home/runner/work/bookbuilderpy/moptipy/docs/build/ \( -type d -name .git -prune \) -o -type f -name "*.html" -print0 | xargs -0 sed -i 's/ src=\"_static\// src=\"\/moptipy\/_static\//g'
        touch /home/runner/work/bookbuilderpy/moptipy/docs/build/.nojekyll
# deploy to github pages
    - name: deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: /home/runner/work/moptipy/moptipy/docs/build/
        single-commit: true
